<a href="https://colab.research.google.com/github/Dev-debasish-09/My_PYtorch/blob/main/DataSet_DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
#forming data
x,y = make_classification(
    n_samples = 10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [5]:
x = torch.tensor(x,dtype=torch.float32)
y = torch.tensor(y,dtype=torch.long)

In [6]:
from torch.utils.data import Dataset,DataLoader

In [14]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    # Here yOu can apply any transformation You want (Agumentation,grayscale,limitization,and many More)
    return self.features[index],self.labels[index]

In [15]:
dataset = CustomDataset(x,y)

In [16]:
len(dataset)

10

In [17]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [18]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [19]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print('.'*50)

tensor([[-0.9382, -0.5430],
        [-0.5872, -1.9717]])
tensor([1, 0])
..................................................
tensor([[-1.9629, -0.9923],
        [ 1.7774,  1.5116]])
tensor([0, 1])
..................................................
tensor([[ 1.0683, -0.9701],
        [-2.8954,  1.9769]])
tensor([1, 0])
..................................................
tensor([[-1.1402, -0.8388],
        [ 1.7273, -1.1858]])
tensor([0, 1])
..................................................
tensor([[-0.7206, -0.9606],
        [ 1.8997,  0.8344]])
tensor([0, 1])
..................................................
