<a href="https://colab.research.google.com/github/Dev-debasish-09/My_PYtorch/blob/main/DataSet_DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
#forming data
x,y = make_classification(
    n_samples = 10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [5]:
x = torch.tensor(x,dtype=torch.float32)
y = torch.tensor(y,dtype=torch.long)

In [6]:
from torch.utils.data import Dataset,DataLoader

In [14]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    # Here yOu can apply any transformation You want (Agumentation,grayscale,limitization,and many More)
    return self.features[index],self.labels[index]

In [15]:
dataset = CustomDataset(x,y)

In [16]:
len(dataset)

10

In [17]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [18]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [19]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print('.'*50)

tensor([[-0.9382, -0.5430],
        [-0.5872, -1.9717]])
tensor([1, 0])
..................................................
tensor([[-1.9629, -0.9923],
        [ 1.7774,  1.5116]])
tensor([0, 1])
..................................................
tensor([[ 1.0683, -0.9701],
        [-2.8954,  1.9769]])
tensor([1, 0])
..................................................
tensor([[-1.1402, -0.8388],
        [ 1.7273, -1.1858]])
tensor([0, 1])
..................................................
tensor([[-0.7206, -0.9606],
        [ 1.8997,  0.8344]])
tensor([0, 1])
..................................................


Working with the previous problem

In [20]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [22]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [24]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [26]:
x_train_tensor = torch.from_numpy(X_train).type(torch.float32)
x_test_tensor = torch.from_numpy(X_test).type(torch.float32)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


In [27]:
from torch.utils.data import Dataset,DataLoader
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index],self.labels[index]

In [28]:
train_dataset = CustomDataset(x_train_tensor,y_train_tensor)
test_dataset = CustomDataset(x_test_tensor,y_test_tensor)

In [29]:
train_dataloader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_dataloader = DataLoader(test_dataset,batch_size=32,shuffle=True)

In [33]:
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [34]:
learning_rate = 0.1
epochs = 30

In [35]:
model = MySimpleNN(x_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
loss_function = nn.BCELoss()

In [40]:
for epoch in range(epochs):

  for batch_features,batch_labels in train_dataloader:

    y_pred = model(batch_features)

    loss = loss_function(y_pred,batch_labels.view(-1,1).float())

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

  print(f'Epochs:{epoch+1},loss:{loss.item()}')

Epochs:1,loss:0.05677393078804016
Epochs:2,loss:0.011285548098385334
Epochs:3,loss:0.01605977490544319
Epochs:4,loss:0.02509138360619545
Epochs:5,loss:0.0006734993075951934
Epochs:6,loss:0.06671126931905746
Epochs:7,loss:0.021954180672764778
Epochs:8,loss:0.06372509896755219
Epochs:9,loss:0.003089819336310029
Epochs:10,loss:0.05057724937796593
Epochs:11,loss:0.042223382741212845
Epochs:12,loss:0.010099480859935284
Epochs:13,loss:0.06061994284391403
Epochs:14,loss:0.19275955855846405
Epochs:15,loss:0.024109525606036186
Epochs:16,loss:0.02915538288652897
Epochs:17,loss:0.11952625960111618
Epochs:18,loss:0.12696121633052826
Epochs:19,loss:0.005740245338529348
Epochs:20,loss:0.10996045917272568
Epochs:21,loss:0.05556267127394676
Epochs:22,loss:0.03262010216712952
Epochs:23,loss:0.01899944432079792
Epochs:24,loss:0.11249469965696335
Epochs:25,loss:0.038016386330127716
Epochs:26,loss:0.7372781038284302
Epochs:27,loss:0.02496376261115074
Epochs:28,loss:0.007489662617444992
Epochs:29,loss:0.00

In [41]:
accuracy_list = []
with torch.no_grad():
  for batch_features,batch_labels in test_dataloader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float()
    accuracy = (y_pred == batch_labels.view(-1,1).float()).float().mean()
    accuracy_list.append(accuracy.item())


In [43]:
overall_accuracy = sum(accuracy_list)/len(accuracy_list)

In [44]:
overall_accuracy

0.96875