In [6]:
# Practice Example
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [7]:
#create dataset
features = torch.rand(10,5)
#create model
model = Model(features.shape[1])
#call model
model(features)

tensor([[0.6515],
        [0.6843],
        [0.6727],
        [0.7175],
        [0.7252],
        [0.7096],
        [0.6669],
        [0.7713],
        [0.6392],
        [0.6766]], grad_fn=<SigmoidBackward0>)

In [9]:
!pip install torchinfo

In [10]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [11]:
#new model with hidden layer
class Model_1(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [12]:
model_1  = Model_1(features.shape[1])
model_1(features)

tensor([[0.5639],
        [0.5585],
        [0.5665],
        [0.5551],
        [0.5641],
        [0.5537],
        [0.5595],
        [0.5501],
        [0.5691],
        [0.5616]], grad_fn=<SigmoidBackward0>)

In [13]:
summary(model_1,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model_1                                  [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [17]:
# using Sequential Container
class Model_2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

In [18]:
model_2 = Model_2(features.shape[1])
model_2(features)

tensor([[0.4495],
        [0.4688],
        [0.4348],
        [0.4417],
        [0.4528],
        [0.4098],
        [0.4594],
        [0.3965],
        [0.4316],
        [0.4688]], grad_fn=<SigmoidBackward0>)

In [19]:
summary(model_2,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model_2                                  [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

***EXample - Working With Breast Cancer Detection With NN-Module***


In [20]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [22]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [24]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [32]:
x_train_tensor = torch.from_numpy(X_train).type(torch.float32)
x_test_tensor = torch.from_numpy(X_test).type(torch.float32)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


In [33]:
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss(self,y_pred,y_true):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(y_true*torch.log(y_pred)+(1-y_true)*torch.log(1-y_pred))
    return loss.mean()

In [37]:
learning_rate = 0.1
epochs = 30
my_model = MySimpleNN(x_train_tensor.shape[1])
for epoch in range(epochs):
  y_pred = my_model(x_train_tensor)
  loss = my_model.loss(y_pred,y_train_tensor)
  loss.backward()
  with torch.no_grad():
    my_model.linear.weight -= learning_rate*my_model.linear.weight.grad
    my_model.linear.bias -= learning_rate*my_model.linear.bias.grad
  my_model.linear.weight.grad.zero_()
  my_model.linear.bias.grad.zero_()
  print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 0.7316862344741821
Epoch 2, Loss: 0.7147998213768005
Epoch 3, Loss: 0.7049287557601929
Epoch 4, Loss: 0.6989150643348694
Epoch 5, Loss: 0.6949673891067505
Epoch 6, Loss: 0.6921408772468567
Epoch 7, Loss: 0.689950704574585
Epoch 8, Loss: 0.6881476640701294
Epoch 9, Loss: 0.6865993142127991
Epoch 10, Loss: 0.6852322816848755
Epoch 11, Loss: 0.6840029954910278
Epoch 12, Loss: 0.6828838586807251
Epoch 13, Loss: 0.6818562150001526
Epoch 14, Loss: 0.6809064149856567
Epoch 15, Loss: 0.6800243854522705
Epoch 16, Loss: 0.6792019605636597
Epoch 17, Loss: 0.6784328818321228
Epoch 18, Loss: 0.6777116060256958
Epoch 19, Loss: 0.6770340204238892
Epoch 20, Loss: 0.6763961315155029
Epoch 21, Loss: 0.6757948994636536
Epoch 22, Loss: 0.6752272248268127
Epoch 23, Loss: 0.6746909618377686
Epoch 24, Loss: 0.6741835474967957
Epoch 25, Loss: 0.6737032532691956
Epoch 26, Loss: 0.6732483506202698
Epoch 27, Loss: 0.6728169918060303
Epoch 28, Loss: 0.6724079251289368
Epoch 29, Loss: 0.672019660472

In [45]:
#using Binary cross entropy instead of my own loss function
class MySimpleNN_1(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [46]:
loss_function = nn.BCELoss()

In [47]:
learning_rate = 0.1
epochs = 30

In [48]:
my_model = MySimpleNN_1(x_train_tensor.shape[1])
for epoch in range(epochs):
  y_pred = my_model(x_train_tensor)

  loss = loss_function(y_pred,y_train_tensor.type(torch.float32).view(-1,1))

  loss.backward()

  with torch.no_grad():
    my_model.linear.weight -= learning_rate*my_model.linear.weight.grad
    my_model.linear.bias -= learning_rate*my_model.linear.bias.grad

  my_model.linear.weight.grad.zero_()
  my_model.linear.bias.grad.zero_()

  print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 0.8832248449325562
Epoch 2, Loss: 0.6394490599632263
Epoch 3, Loss: 0.5147225260734558
Epoch 4, Loss: 0.4407768249511719
Epoch 5, Loss: 0.3913508355617523
Epoch 6, Loss: 0.3555692136287689
Epoch 7, Loss: 0.32819604873657227
Epoch 8, Loss: 0.3064019978046417
Epoch 9, Loss: 0.2885211110115051
Epoch 10, Loss: 0.27350547909736633
Epoch 11, Loss: 0.2606610357761383
Epoch 12, Loss: 0.24950850009918213
Epoch 13, Loss: 0.2397053837776184
Epoch 14, Loss: 0.23099981248378754
Epoch 15, Loss: 0.2232019454240799
Epoch 16, Loss: 0.21616573631763458
Epoch 17, Loss: 0.2097766399383545
Epoch 18, Loss: 0.2039433866739273
Epoch 19, Loss: 0.19859212636947632
Epoch 20, Loss: 0.1936623603105545
Epoch 21, Loss: 0.1891038715839386
Epoch 22, Loss: 0.1848745197057724
Epoch 23, Loss: 0.18093860149383545
Epoch 24, Loss: 0.17726565897464752
Epoch 25, Loss: 0.1738293468952179
Epoch 26, Loss: 0.1706068068742752
Epoch 27, Loss: 0.16757819056510925
Epoch 28, Loss: 0.1647258847951889
Epoch 29, Loss: 0.16

In [49]:
with torch.no_grad():
  y_pred = my_model.forward(x_test_tensor)
  y_pred = (y_pred>0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.586334228515625


In [50]:
# using torch.optim
class MySimpleNN_2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [51]:
learning_rate = 0.1
epochs = 30

In [53]:
loss_function = nn.BCELoss()

In [54]:
my_model = MySimpleNN_1(x_train_tensor.shape[1])

#define a optimizer
optimizer = torch.optim.SGD(my_model.parameters(),lr = learning_rate)

for epoch in range(epochs):
  y_pred = my_model(x_train_tensor)

  loss = loss_function(y_pred,y_train_tensor.type(torch.float32).view(-1,1))

  optimizer.zero_grad()

  loss.backward()
  # NOt responsible for writing a long update logic only write the following
  optimizer.step()

  print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 0.5140262246131897
Epoch 2, Loss: 0.4299042522907257
Epoch 3, Loss: 0.37754759192466736
Epoch 4, Loss: 0.34116724133491516
Epoch 5, Loss: 0.3140624463558197
Epoch 6, Loss: 0.2928800880908966
Epoch 7, Loss: 0.27574193477630615
Epoch 8, Loss: 0.2615072727203369
Epoch 9, Loss: 0.24943938851356506
Epoch 10, Loss: 0.2390391230583191
Epoch 11, Loss: 0.22995491325855255
Epoch 12, Loss: 0.2219310998916626
Epoch 13, Loss: 0.21477682888507843
Epoch 14, Loss: 0.2083461880683899
Epoch 15, Loss: 0.20252560079097748
Epoch 16, Loss: 0.1972249150276184
Epoch 17, Loss: 0.19237178564071655
Epoch 18, Loss: 0.1879071146249771
Epoch 19, Loss: 0.18378223478794098
Epoch 20, Loss: 0.17995665967464447
Epoch 21, Loss: 0.1763962358236313
Epoch 22, Loss: 0.17307211458683014
Epoch 23, Loss: 0.16995953023433685
Epoch 24, Loss: 0.16703732311725616
Epoch 25, Loss: 0.1642870455980301
Epoch 26, Loss: 0.16169273853302002
Epoch 27, Loss: 0.15924035012722015
Epoch 28, Loss: 0.15691761672496796
Epoch 29, Los

In [55]:
with torch.no_grad():
  y_pred = my_model.forward(x_test_tensor)
  y_pred = (y_pred>0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.586334228515625
